apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations: {}
  labels:
    operators.coreos.com/servicemeshoperator3.openshift-operators: ''
    operators.coreos.com/servicemeshoperator3.ossm3: ''
  name: servicemeshoperator3
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: servicemeshoperator3
  source: redhat-operators
  sourceNamespace: openshift-marketplace
